name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      runs:
        description: "Choose an env that you want to execute"
        required: true
        default: "ui"
        type: choice
        options:
          - ui
          - api

  pull_request:
    branches: [main]         

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      RUN: dev

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Set env variable
        run: |
          if [ -n "${{ inputs.runs }}" ]; then 
          echo "Setting projects from github.event.inputs.runs"
          echo "RUN=${{ inputs.runs }}" >> $GITHUB_ENV
          fi
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run $ENVIRONMENT
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30